server:
  port: 8903
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2239489555/springcloud-config.git
          username:
          password:
          clone-on-start: true # 开启启动时直接从git获取配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/